### model
model_name_or_path: path/to/your/model

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj, v_proj


### dataset
dataset: dataset
template: your/model
cutoff_len: 1024
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: path/to/save
logging_steps: 10
save_steps: 50000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true


use_robust_tuning: true
prompt_search_space: paft/prompts/robust_traindataset_dataset.xlsx

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
